name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-get-tasks-api
      IMAGE_TAG: v2
      ACR_NAME: sohitacrdev02
      ACR_LOGIN_SERVER: sohitacrdev02.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 7fad8abf-358a-4d48-9409-a3240b110650
          tenant-id: 8ab5781a-7bf2-4b23-8a88-9ac543f6f20f
          subscription-id: 135c8cc3-c5aa-4358-9e11-f2056457e4a5

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
